### ISSUE TITLE
"Additional property samba is not allowed"

### ISSUE THREAD

**Issue by caboj** [thomasheckmann/ps2opl_osx#2]
When I try to build the docker container, I get this error:

`(root) Additional property samba is not allowed`

I've tried to figure out what's causing this issue, but can't get past this error. Any help is appreciated, thanks!

**Comment by guest951** [comment]
I got the same error, I think this happens because the example `docker-compose.yml` has a too old syntax for the newest versions of docker-compose.
I modified the file like this:
```
version: "3"
services:
  samba:
    image: joebiellik/samba-server

    volumes:
      # You must provide a Samba config file
      - ./smb.conf:/etc/samba/smb.conf

      # Shares
      - /Users/me/myshare:/mnt/ps2smb

    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"

    environment:
      - USERNAME=joe
      - PASSWORD=samba
```
However, it is still not working for me, I get `301: Cannot log into SMB server` when I try to connect.
